set autoindent
set shiftwidth=4  " number of spaces line is moved by << or >>
set expandtab     " change tab to requred number of spaces
set tabstop=4     " width of tab
set softtabstop=4 " columns of whitespace removed by backspace
set textwidth=66  " so all fits when 'vsplit' on my screen
set scrolljump=2
set scrolloff=2   " Keep at least n lines above/below cursor
" set mousehide     " Hide the mouse when typing
" set number        " Set line numbering
syntax on

" In insert mode, use ctrl+v to insert your system's clipboard content
" (Paste mode)   ! from Aaron:
" imap <C-v> <Esc>:set paste<CR>"+P :set nopaste<CR>a
" the above line is not needed for copy paste to work
" and interferes with ability to enter control characters!

" The following is to do with Vundle:   !!! VUNDLE  !!!
" https://www.linuxfordevices.com/tutorials/linux/vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize Vundle
" The directory should be changed in case you download it somewhere else
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()    " VundleBeginListing

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" All the plugins to be installed are to be mentioned here
" inside the vundle#begin and vundle#end

Plugin 'alvan/vim-closetag'

call vundle#end()           " VundleEndListing
filetype plugin indent on   " required
" ...end of Vundle.                   !!! VundleEnd  !!

let g:closetag_filenames = '*.html,*.xhtml,*.phtml'

" Don't know where the following came from or what it does:
" if has("autocmd")
"   au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
" endif
